apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-rolebinding-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: controller
