apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-rolebinding-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: klm-controller-role-leader-election
subjects:
- kind: ServiceAccount
  name: controller
