- op: replace
  path: /spec/template/spec/containers/0/args/16
  value: --kyma-requeue-success-interval=1h
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --kyma-requeue-warning-interval=1h
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --kyma-requeue-error-interval=1h
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --kyma-requeue-busy-interval=1s
